[package]
name    = "screenruster-saver-laughing_man"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

[dependencies]
nalgebra           = "*"
screenruster-saver = { git = "https://github.com/meh/screenruster-saver" }
